# Generated by Django 2.2.2 on 2020-02-27 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200225_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='message',
            field=models.CharField(default='', max_length=255),
        ),
    ]
