# Generated by Django 2.2.2 on 2020-02-27 20:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_post_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 27, 21, 5, 48, 31070), verbose_name='date_published'),
        ),
        migrations.AlterField(
            model_name='post',
            name='message',
            field=models.TextField(default='', max_length=255),
        ),
    ]
